# Generated by Django 5.0.7 on 2025-04-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('game_date', models.DateTimeField()),
                ('is_finished', models.BooleanField(default=False)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('home_club_placement', models.JSONField(default=dict)),
                ('away_club_placement', models.JSONField(default=dict)),
                ('away_club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_club', to='club.club')),
                ('best_player', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='player.player')),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_club', to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ГОООЛ!', 'ГОООЛ!')], max_length=63)),
                ('minutes', models.PositiveSmallIntegerField(default=0)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='Statictic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xg', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('goal_attempts', models.PositiveSmallIntegerField(default=0)),
                ('shots', models.PositiveSmallIntegerField(default=0)),
                ('saves', models.PositiveSmallIntegerField(default=0)),
                ('corners', models.PositiveSmallIntegerField(default=0)),
                ('fouls', models.PositiveSmallIntegerField(default=0)),
                ('passes', models.PositiveSmallIntegerField(default=0)),
                ('tackles', models.PositiveSmallIntegerField(default=0)),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0)),
                ('red_cards', models.PositiveSmallIntegerField(default=0)),
                ('shots_on_target', models.PositiveSmallIntegerField(default=0)),
                ('shots_off_target', models.PositiveSmallIntegerField(default=0)),
                ('blocked_shots', models.PositiveSmallIntegerField(default=0)),
                ('shots_inside_box', models.PositiveSmallIntegerField(default=0)),
                ('shots_outside_box', models.PositiveSmallIntegerField(default=0)),
                ('big_chances_missed', models.PositiveSmallIntegerField(default=0)),
                ('offsides', models.PositiveSmallIntegerField(default=0)),
                ('possession', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('big_chances', models.PositiveSmallIntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.club')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.game')),
            ],
        ),
    ]
