# Generated by Django 5.0.7 on 2025-05-09 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        ('game', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='best_player',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='player.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_club', to='club.club'),
        ),
        migrations.AddField(
            model_name='gamestatistic',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.club'),
        ),
        migrations.AddField(
            model_name='gamestatistic',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.game'),
        ),
        migrations.AddField(
            model_name='history',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.action'),
        ),
        migrations.AddField(
            model_name='history',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.game'),
        ),
        migrations.AddField(
            model_name='history',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='player.player'),
        ),
    ]
