# Generated by Django 5.0.7 on 2025-05-17 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='season.season'),
        ),
        migrations.AddField(
            model_name='game',
            name='tour',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
