# Generated by Django 5.0.7 on 2025-05-28 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_gamestatistic_big_chances_and_more'),
        ('player', '0003_alter_playerstatistic_all_shotsontarget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='player.player'),
        ),
    ]
