# Generated by Django 5.0.7 on 2025-04-15 18:14

import django.db.models.deletion
import player.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_title', models.DecimalField(decimal_places=2, max_digits=3)),
                ('minutes_played', models.PositiveSmallIntegerField(default=0)),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('total_shots', models.PositiveSmallIntegerField(default=0)),
                ('all_passes', models.PositiveSmallIntegerField(default=0)),
                ('accurate_passes', models.PositiveSmallIntegerField(default=0)),
                ('chances_created', models.PositiveSmallIntegerField(default=0)),
                ('all_shots', models.PositiveSmallIntegerField(default=0)),
                ('shotsOnTarget', models.PositiveSmallIntegerField(default=0)),
                ('touches', models.PositiveSmallIntegerField(default=0)),
                ('touches_opp_box', models.PositiveSmallIntegerField(default=0)),
                ('passes_into_final_third', models.PositiveSmallIntegerField(default=0)),
                ('all_crosses', models.PositiveSmallIntegerField(default=0)),
                ('accurate_crosses', models.PositiveSmallIntegerField(default=0)),
                ('all_long_balls', models.PositiveSmallIntegerField(default=0)),
                ('accurate_long_balls', models.PositiveSmallIntegerField(default=0)),
                ('corners', models.PositiveSmallIntegerField(default=0)),
                ('dispossessed', models.PositiveSmallIntegerField(default=0)),
                ('all_tackles', models.PositiveSmallIntegerField(default=0)),
                ('success_tackles', models.PositiveSmallIntegerField(default=0)),
                ('clearances', models.PositiveSmallIntegerField(default=0)),
                ('interceptions', models.PositiveSmallIntegerField(default=0)),
                ('defensive_actions', models.PositiveSmallIntegerField(default=0)),
                ('recoveries', models.PositiveSmallIntegerField(default=0)),
                ('dribbled_past', models.PositiveSmallIntegerField(default=0)),
                ('duel_won', models.PositiveSmallIntegerField(default=0)),
                ('duel_lost', models.PositiveSmallIntegerField(default=0)),
                ('ground_duels', models.PositiveSmallIntegerField(default=0)),
                ('success_ground_duels', models.PositiveSmallIntegerField(default=0)),
                ('aerials', models.PositiveSmallIntegerField(default=0)),
                ('success_aerials', models.PositiveSmallIntegerField(default=0)),
                ('was_fouled', models.PositiveSmallIntegerField(default=0)),
                ('fouls', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('photo', models.FileField(upload_to=player.models.player_photo_path)),
                ('surname', models.CharField(max_length=63)),
                ('name', models.CharField(max_length=63)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('country', models.CharField(choices=[('Россия', 'Россия'), ('США', 'США'), ('Китай', 'Китай')], max_length=63)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.club')),
                ('position', models.ManyToManyField(to='player.position')),
            ],
        ),
    ]
