# Generated by Django 5.0.7 on 2025-05-09 17:40

import django.db.models.deletion
import player.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('matches_uppercase', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('minutes_played', models.PositiveIntegerField(blank=True, default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('goals', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('shots', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('ShotsOnTarget', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('assists', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('successful_passes', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('successful_passes_accuracy', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('long_balls_accurate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('long_ball_succeeeded_accuracy', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('chances_created', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('dribbles_succeeded', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('won_contest_subtitle', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('touches', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('touches_opp_box', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('dispossessed', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('fouls_won', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('tackles_succeeded', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('tackles_succeeded_percent', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('duel_won', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('duel_won_percent', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('aerials_won', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('aerials_won_percent', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('interceptions', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('shot_blocked', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('fouls', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('recoveries', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('poss_won_att_3rd_team_title', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('dribbled_past', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('yellow_cards', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('red_cards', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('crosses_succeeeded', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('crosses_succeeeded_accuracy', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'player_statistic',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.PositiveIntegerField(db_index=True, unique=True)),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to=player.models.player_photo_path)),
                ('photo_url', models.TextField(blank=True, default=None, null=True)),
                ('surname', models.CharField(max_length=63)),
                ('name', models.CharField(max_length=63)),
                ('height', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('country', models.CharField(max_length=63)),
                ('position_ids', models.JSONField(default=list)),
                ('preferred_foot', models.CharField(blank=True, default=None, max_length=63, null=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='club.club')),
                ('statistic', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player', to='player.playerstatistic')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_title', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('minutes_played', models.IntegerField(blank=True, default=0)),
                ('goals', models.IntegerField(blank=True, default=0)),
                ('assists', models.IntegerField(blank=True, default=0)),
                ('total_shots', models.IntegerField(blank=True, default=0)),
                ('accurate_passes', models.CharField(max_length=15)),
                ('chances_created', models.IntegerField(blank=True, default=0)),
                ('touches', models.IntegerField(blank=True, default=0)),
                ('touches_opp_box', models.IntegerField(blank=True, default=0)),
                ('passes_into_final_third', models.IntegerField(blank=True, default=0)),
                ('accurate_crosses', models.CharField(max_length=15)),
                ('long_balls_accurate', models.CharField(max_length=15)),
                ('corners', models.IntegerField(blank=True, default=0)),
                ('dispossessed', models.IntegerField(blank=True, default=0)),
                ('tackles_succeeded', models.CharField(max_length=15)),
                ('clearances', models.IntegerField(blank=True, default=0)),
                ('headed_clearance', models.IntegerField(blank=True, default=0)),
                ('interceptions', models.IntegerField(blank=True, default=0)),
                ('defensive_actions', models.IntegerField(blank=True, default=0)),
                ('recoveries', models.IntegerField(blank=True, default=0)),
                ('dribbled_past', models.IntegerField(blank=True, default=0)),
                ('duel_won', models.IntegerField(blank=True, default=0)),
                ('duel_lost', models.IntegerField(blank=True, default=0)),
                ('ground_duels_won', models.CharField(max_length=15)),
                ('aerials_won', models.CharField(max_length=15)),
                ('was_fouled', models.IntegerField(blank=True, default=0)),
                ('fouls', models.IntegerField(blank=True, default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
            ],
            options={
                'db_table': 'player_game_statistic',
            },
        ),
    ]
