# Generated by Django 5.0.7 on 2025-05-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatistic',
            name='all_ShotsOnTarget',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playerstatistic',
            name='all_assists',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playerstatistic',
            name='all_chances_created',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playerstatistic',
            name='all_dispossessed',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playerstatistic',
            name='all_dribbles_succeeded',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playerstatistic',
            name='all_goals',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playerstatistic',
            name='all_red_cards',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playerstatistic',
            name='all_yellow_cards',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
