# Generated by Django 5.0.7 on 2025-05-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='matches_uppercase',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='minutes_played',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='statistic',
            name='started',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
