# Generated by Django 5.0.7 on 2025-05-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_playerstatistic_all_shotsontarget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistic',
            name='all_ShotsOnTarget',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='all_assists',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='all_chances_created',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='all_dispossessed',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='all_dribbles_succeeded',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='all_goals',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='all_red_cards',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='all_yellow_cards',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
