# Generated by Django 5.0.7 on 2025-05-28 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        ('player', '0003_alter_playerstatistic_all_shotsontarget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='club', to='club.club'),
        ),
    ]
