# Generated by Django 5.0.7 on 2025-05-30 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_alter_player_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='statistic',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player', to='player.playerstatistic'),
        ),
    ]
