# Generated by Django 5.0.7 on 2025-06-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_role_rename_position_ids_player_role_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestatistic',
            name='goals_conceded',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playergamestatistic',
            name='keeper_diving_save',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playergamestatistic',
            name='keeper_high_claim',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playergamestatistic',
            name='keeper_sweeper',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playergamestatistic',
            name='player_throws',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playergamestatistic',
            name='punches',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playergamestatistic',
            name='saves',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playergamestatistic',
            name='saves_inside_box',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
