# Generated by Django 5.0.7 on 2025-06-12 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_playergamestatistic_goals_conceded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='role_ids',
        ),
        migrations.AddField(
            model_name='player',
            name='primary_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='primary_players', to='player.position'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='injury',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='injured_players', to='player.injury'),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ManyToManyField(related_name='players', to='player.position'),
        ),
    ]
