# Generated by Django 5.0.7 on 2025-05-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('club_ids', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'season',
                'ordering': ['-id'],
            },
        ),
    ]
