ATTACKING_MIDFIELDER_WEIGHTS = {
    "poss_won_att_3rd_team_title": (4,False),
    "dribbles_succeeded": (6,False),
    "dispossessed": (6, True),
    "assists": (8,False),
    "all_assists": (9,False),
    "chances_created": (9,False),
    "all_goals": (6,False),
    "ShotsOnTarget": (5,False),
    "successful_passes_accuracy": (5, False),
    "touches_opp_box": (4,False),
    "Голевая конверсия": (3,False),
    "goals": (4,False),
    "recoveries": (7, False),
    "won_contest_subtitle": (2, False),

    "poss_won_att_3rd_team_title": (6,False),

    "all_goals": (7,False),
    "goals": (7,False),
    "Минут на гол": (4, True),
    "recoveries": (5, False),
    "ShotsOnTarget": (5,False),
    "all_assists": (8,False),
    "chances_created": (6,False),
    "dribbles_succeeded": (7,False),
    "aerials_won_percent": (4,False),
    "aerials_won": (3,False),
    "dispossessed": (6, True),
    "won_contest_subtitle": (5, False),
    "successful_passes_accuracy": (5, False),
    "touches_opp_box": (8, False),
    "assists": (7, False),
    "Голевая конверсия": (2, False),


}