CENTRAL_MIDFIELDER_WEIGHTS = {
    "duel_won_percent": (4,False),
    "tackles_succeeded_percent": (4,False),
    "interceptions": (3,False),
    "dribbles_succeeded": (7,False),
    "dispossessed": (4, True),
    "won_contest_subtitle": (6,False),
    "assists": (7,False),
    "chances_created": (7,False),
    "successful_passes": (6,False),
    "successful_passes_accuracy": (4,False),
    "recoveries": (3,False),
    "shot_blocked": (2,False),
    "all_assists": (7,False),
    "touches_opp_box": (4, False),
    "Голевая конверсия": (5, False),
    "goals": (4, False),
    "poss_won_att_3rd_team_title": (2, False),
}