STRIKER_WEIGHTS = {
    "poss_won_att_3rd_team_title": (8,False),
    "all_goals": (7,False),
    "goals": (7,False),
    "Минут на гол": (4, True),
    "recoveries": (5, False),
    "ShotsOnTarget": (5,False),
    "all_assists": (8,False),
    "chances_created": (6,False),
    "dribbles_succeeded": (7,False),
    "aerials_won_percent": (4,False),
    "aerials_won": (3,False),
    "dispossessed": (6, True),
    "won_contest_subtitle": (5, False),
    "successful_passes_accuracy": (3.6, False),
    "touches_opp_box": (9, False),
    "assists": (7, False),
    "Голевая конверсия": (2, False),
}
