# Generated by Django 5.0.7 on 2025-04-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=63)),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='.../media/clubs')),
                ('photo_url', models.TextField(blank=True, default=None, null=True)),
                ('stadium_name', models.CharField(max_length=63)),
                ('stadium_count_of_sits', models.PositiveIntegerField(default=0)),
                ('city_name', models.CharField(max_length=63)),
                ('placement', models.JSONField(default=dict)),
            ],
        ),
    ]
